name: Auto Commits

on:
  schedule:
    - cron: '0 0 */3 * *'  # Every 3 days at midnight UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make 4 commits
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "ananyajaiswal2810"
          git config user.email "jananya272@gmail.com"
          
          for i in {1..4}
          do
            echo "$(date) - Commit #$i" >> commit_log.txt
            git add commit_log.txt
            git commit -m "Auto commit #$i on $(date)"
          done

          git remote set-url origin https://x-access-token:${TOKEN}@github.com/ananyajaiswal2810/auto-commit-bot.git
          git push origin main
